name: hangmania
description: "HangMania: An HangMan game for android."
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^13.1.0
  shared_preferences: ^2.2.2
  http: ^0.13.6
  logger: ^2.0.2+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: ^2.8.8

flutter:
  uses-material-design: true
  generate: true
